title: S.T.A.L.K.E.R. TTRPG
description: Настольная ролевая система в мире S.T.A.L.K.E.R
theme: just-the-docs

url: https://ivatar39.github.io/stalker-ttrpg

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
