title: S.T.A.L.K.E.R. TTRPG
description: Настольная ролевая система в мире S.T.A.L.K.E.R
theme: just-the-docs

url: https://ivatar39.github.io/stalker-ttrpg

color_scheme: dark
favicon_ico: "/assets/images/favicon.ico"

# show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_timestamp: true 
# uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_edit_time_format: "%d.%m.%Y в %H:%M %Z %z"

aux_links:
  "S.T.A.L.K.E.R. на GitHub":
    - "https://github.com/ivatar39/stalker-ttrpg"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true