title: S.T.A.L.K.E.R. TTRPG
description: Настольная ролевая система в мире S.T.A.L.K.E.R
theme: just-the-docs

url: https://ivatar39.github.io/stalker-ttrpg

color_scheme: dark
favicon_ico: "/assets/images/favicon.ico"

